# -*- coding: utf-8 -*-
"""
-------------------------------------------------------------------------------------------------------------------------
uv_structures.py
-------------------------------------------------------------------------------------------------------------------------
Created on Wed Apr  3 15:02:00 2024

@author: Andres Cremades Botella

File to define the uv structures:
    Class:
        - uv_structure : Class of the Reynolds stress coherent structures.
"""
# -----------------------------------------------------------------------------------------------------------------------
# Import packages for all functions
# -----------------------------------------------------------------------------------------------------------------------
import os
import numpy as np
import h5py
from py_bin.py_class.flow_field import flow_field

# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------
# Define functions
# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------

class hunt_structure():
    """
    .....................................................................................................................
    # streak_structure: Class of the streak coherent structures.
        * Functions:
            - __init__ : initialization function
            - calculate_matstruc : calculate the matrix containing the nodes included in the transverse Reynolds stress
                                   structures.
            - segment_struc      : calculates the segmentation of the domain based on the transverse Reynolds stress
                                   structures.
            - save_struc         : function to save the structures
            - read_struc         : function to read the structures
        * Variables:
            - uvw_folder  : folder of the velocity flow fields
            - uvw_file    : file of the velocity flow fields
            - Hperc       : percolation index
            - index       : index of the field to read
            - dx          : downsampling in the streamwise direction
            - dy          : downsampling in the wall-normal direction
            - dz          : downsampling in the streamwise direction
            - L_x         : streamwise dimension of the channel
            - L_y         : wall-normal dimension of the channel
            - L_z         : spanwise dimension of the channel
            - rey         : friction Reynolds number
            - utau        : frictin velocity
            - padding     : padding of the fields
            - data_folder : folder containing the data generated by the code
            - umean_file  : mean velocity file
            - urms_file   : rms velocity file
            - sym_quad    : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                            of the structure
            - filvol      : volume for filtering the structures
            - shap_folder : folder of the SHAP values
            - shap_file   : file of the SHAP values
            - folder      : folder to save the uv structures
            - file        : file to save the uv structures
            - shpy        : shape of the tensors in the wall-normal direction
            - shpx        : shape of the tensors in the streamwise direction
            - shpz        : shape of the tensors in the spanwise direction
            - mat_struc   : matrix defining the nodes contained in the structures
            - field_u     : field of the streamwise velocity
            - field_v     : field of the wall-normal velocity
        * Classes:
            - structures  : class containing the structure information (read from py_bin.py_class.structures)
    .....................................................................................................................
    """
    def __init__(self,data_in={"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                               "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                               "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"Umean.txt",
                               "urms_file":"Urms.txt","sym_quad":True,"filvol":2.7e4,
                               "shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                               "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_huntstruc/",
                               "file":"P125_21pi_vu.$INDEX$.h5.hunt","padding":15,"data_type":"float32"}):
        """
        .................................................................................................................
        # __init__
        .................................................................................................................
        Function to initilize the uv structures.

        Parameters
        ----------
        data_in : dict, optional
            Data for initilizing the uv structure.
            The default is {"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                            "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                            "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"Umean.txt",
                            "filvol":2.7e4,"shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                            "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_huntstruc/",
                            "file":"P125_21pi_vu.$INDEX$.h5.hunt","padding":15,"data_type":"float32"}.
            Data:
                - uvw_folder  : folder of the velocity flow fields
                - uvw_file    : file of the velocity flow fields
                - Hperc       : percolation index
                - index       : index of the field to read
                - dx          : downsampling in the streamwise direction
                - dy          : downsampling in the wall-normal direction
                - dz          : downsampling in the streamwise direction
                - L_x         : streamwise dimension of the channel
                - L_y         : wall-normal dimension of the channel
                - L_z         : spanwise dimension of the channel
                - rey         : friction Reynolds number
                - utau        : frictin velocity
                - padding     : padding of the fields
                - data_folder : folder containing the data generated by the code
                - umean_file  : mean velocity file
                - urms_file   : rms velocity file
                - sym_quad    : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                                of the structure
                - filvol      : volume for filtering the structures
                - shap_folder : folder of the SHAP values
                - shap_file   : file of the SHAP values
                - folder      : folder to save the uv structures
                - file        : file to save the uv structures
                - padding     : padding of the fields
                - data_type   : type of float used for the data (float16, float32...)
        Returns
        -------
        None.

        """
        # -----------------------------------------------------------------------------------------------------------------
        # Import dataset
        # -----------------------------------------------------------------------------------------------------------------
        from py_bin.py_functions.read_velocity import read_velocity
        
        # -----------------------------------------------------------------------------------------------------------------
        # Read data
        # -----------------------------------------------------------------------------------------------------------------
        self.uvw_folder  = str(data_in["uvw_folder"])
        self.uvw_file    = str(data_in["uvw_file"])
        self.Hperc       = float(data_in["Hperc"])
        self.index       = int(data_in["index"])
        self.down_x      = int(data_in["dx"])
        self.down_y      = int(data_in["dy"])
        self.L_x         = float(data_in["L_x"])
        self.L_y         = float(data_in["L_y"])
        self.rey         = float(data_in["rey"])
        self.utau        = float(data_in["utau"])
        self.padding     = int(data_in["padding"])
        self.data_folder = str(data_in["data_folder"])
        self.umean_file  = str(data_in["umean_file"])
        self.urms_file   = str(data_in["urms_file"])
        self.sym_quad    = bool(data_in["sym_quad"])
        self.filvol      = float(data_in["filvol"])
        self.shap_folder = str(data_in["shap_folder"])
        self.shap_file   = str(data_in["shap_file"])
        self.folder      = str(data_in["folder"])
        self.file        = str(data_in["file"])
        self.data_type   = str(data_in["data_type"])

        # -----------------------------------------------------------------------------------------------------------------
        # Create the flow field (2D)
        # -----------------------------------------------------------------------------------------------------------------
        Data_flow = {"folder":self.uvw_folder,"file":self.uvw_file,"down_x":self.down_x,"down_y":self.down_y,
                     "L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,"utau":self.utau}
        flowfield = flow_field(data_in=Data_flow)
        flowfield.shape_tensor()

        # -----------------------------------------------------------------------------------------------------------------
        # Calculate the shape of the fields
        # -----------------------------------------------------------------------------------------------------------------
        self.shpy = flowfield.shpy
        self.shpx = flowfield.shpx

        # -----------------------------------------------------------------------------------------------------------------
        # Read the velocity (u and v only)
        # -----------------------------------------------------------------------------------------------------------------
        data_read_vel = {"folder":self.uvw_folder,"file":self.uvw_file,"index":self.index,
                         "dx":self.down_x,"dy":self.down_y,"shpx":self.shpx,"shpy":self.shpy,
                         "padding":0,"data_folder":self.data_folder,"umean_file":self.umean_file}
        data_vel     = read_velocity(data_in=data_read_vel)
        self.field_u = data_vel["uu"]
        self.field_v = data_vel["vv"]
        
    def calculate_matstruc(self):
        """        
        .................................................................................................................
        # calculate_matstruc
        .................................................................................................................
        Function to calculate the matrix of the nodes belonging a structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # The definition of the streaks is not implemented
        # ---------------------------------------------------------------------------------------------------------------
    
    def segment_struc(self):
        """       
        .................................................................................................................
        # segment_struc
        ................................................................................................................. 
        Function to segment the domain into the different structures

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # The definition of the streaks is not implemented
        # ---------------------------------------------------------------------------------------------------------------
    
    def save_struc(self):
        """
        .................................................................................................................
        # save_struc
        .................................................................................................................
        Function to save the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # The definition of the streaks is not implemented
        # ---------------------------------------------------------------------------------------------------------------
        
    def read_struc(self):
        """
        .................................................................................................................
        # read_struc
        .................................................................................................................
        Function to read the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        print('Reading: '+file_Q_ii,flush=True)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the file with the saved information
        # ---------------------------------------------------------------------------------------------------------------
        file           = h5py.File(file_Q_ii,'r')
        self.mat_struc = np.array(file['Qs'])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Define the structure class
        # ---------------------------------------------------------------------------------------------------------------
        data_struc      = {"mat_struc":self.mat_struc,"field_1":self.field_u,"field_2":self.field_v,
                           "field_3":np.zeros_like(self.field_u),"flag_sign":False,"uvw_folder":self.uvw_folder,
                           "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,
                           "L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,"utau":self.utau,
                           "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                           "shap_file":self.shap_file}
        self.structures = structures(data_in=data_struc)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the rest of the data
        # ---------------------------------------------------------------------------------------------------------------
        self.structures.mat_segment          = np.array(file['Qs_segment'])
        self.structures.mat_segment_filtered = np.array(file['Qs_segment_filtered'])
        self.structures.dim_x                = np.array(file['dim_x'])
        self.structures.dim_y                = np.array(file['dim_y'])
        self.structures.dim_z                = np.array(file['dim_z'])
        self.structures.ymin                 = np.array(file['ymin'])
        self.structures.ymax                 = np.array(file['ymax'])
        self.structures.vol                  = np.array(file['vol'])
        self.structures.boxvol               = np.array(file['volbox'])
        self.structures.cg_xbox              = np.array(file['cg_xbox'])
        self.structures.cg_ybox              = np.array(file['cg_ybox'])
        self.structures.cg_zbox              = np.array(file['cg_zbox'])
        self.structures.cg_x                 = np.array(file['cg_x'])
        self.structures.cg_y                 = np.array(file['cg_y'])
        self.structures.cg_z                 = np.array(file['cg_z'])
        self.structures.uv_uvtot             = np.array(file['uv_uvtot'])
        self.structures.k_ktot               = np.array(file['k_ktot'])
        self.structures.u1u2                 = np.array(file['uv_uvtot'])
        self.structures.k_ktot               = np.array(file['k_ktot'])
        try:
            self.shap                        = np.array(file['shap'])
        except:
            pass
            
    def reconstruct_fromprevious(self, data_in=None):
        raise NotImplementedError("3D legacy helper, not supported in 2D PIV.")

    def add_SHAP(self,data_in={"nsamples":1}):
        """
        .................................................................................................................
        # add_SHAP
        .................................................................................................................
        Function for adding the total SHAP value of each structure to the structures file
        
        Parameters
        ----------
        data_in : dict, optional
            Name of the folder and file of the file of the previous data.
            The default is {"nsamples":1}.
            Data:
                - nsamples : number of samples of the shap
        
        Returns
        -------
        None.
        
        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.shap_config import shap_config
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        nsamples = int(data_in["nsamples"])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the structure file
        # ---------------------------------------------------------------------------------------------------------------
        self.read_struc()
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the SHAP value of the structure and save it
        # ---------------------------------------------------------------------------------------------------------------
        data_shap = {"shap_folder":self.shap_folder,"shap_file":self.shap_file,"uvw_folder":self.uvw_folder,
                     "uvw_file":self.uvw_file,"padding":self.padding,"dx":self.down_x,"dy":self.down_y,
                     "data_folder":"-","umean_file":"-","unorm_file":"-","L_x":self.L_x,
                     "L_y":self.L_y,"rey":self.rey,"utau":self.utau,"ngpu":0,"field_ini":0,
                     "field_fin":0,"field_delta":0,"model_folder":"-","model_read":"-","nfil":0,"stride":0,
                     "activation":"-","kernel":0,"pooling":0,"delta_pred":0,"nsamples":nsamples,"nsamples_max":0,
                     "data_type":self.data_type,"error_file":"-","umax_file":"-","urmspred_file":"-",
                     "mean_norm":"-","tfrecord_folder":"-","nrep_field":0,"shap_batch":0,"repeat_exist":False,
                     "flag_model":False}
        shap_model = shap_config(data_in=data_shap)
        self.shap  = shap_model.structure_shap(data_in={"mat_segment":self.structures.mat_segment,
                                                        "index_ii":self.index})["SHAP"]
        self.save_struc()
        
