# -*- coding: utf-8 -*-
"""
-------------------------------------------------------------------------------------------------------------------------
shap_structures.py
-------------------------------------------------------------------------------------------------------------------------
Created on Wed Apr  3 15:02:00 2024

@author: Andres Cremades Botella

File to define the uv structures:
    Class:
        - shap_structure : Class of the SHAP value coherent structures.
"""
# -----------------------------------------------------------------------------------------------------------------------
# Import packages for all functions
# -----------------------------------------------------------------------------------------------------------------------
import os
import numpy as np
import h5py
from py_bin.py_class.flow_field import flow_field

# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------
# Define functions
# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------

class shap_structure():
    """
    .....................................................................................................................
    # shap_structure: Class of the SHAP value coherent structures.
        * Functions:
            - __init__ : initialization function
            - calculate_matstruc : calculate the matrix containing the nodes included in the transverse Reynolds stress
                                   structures.
            - segment_struc      : calculates the segmentation of the domain based on the transverse Reynolds stress
                                   structures.
            - save_struc         : function to save the structures
            - read_struc         : function to read the structures
        * Variables:
            - uvw_folder  : folder of the velocity flow fields
            - uvw_file    : file of the velocity flow fields
            - Hperc       : percolation index
            - index       : index of the field to read
            - dx          : downsampling in the streamwise direction
            - dy          : downsampling in the wall-normal direction
            - dz          : downsampling in the streamwise direction
            - L_x         : streamwise dimension of the channel
            - L_y         : wall-normal dimension of the channel
            - L_z         : spanwise dimension of the channel
            - rey         : friction Reynolds number
            - utau        : frictin velocity
            - padding     : padding of the fields
            - data_folder : folder containing the data generated by the code
            - umean_file  : mean velocity file
            - urms_file   : rms velocity file
            - sym_quad    : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                            of the structure
            - filvol      : volume for filtering the structures
            - shap_folder : folder of the SHAP values
            - shap_file   : file of the SHAP values
            - folder      : folder to save the uv structures
            - file        : file to save the uv structures
            - shpy        : shape of the tensors in the wall-normal direction
            - shpx        : shape of the tensors in the streamwise direction
            - shpz        : shape of the tensors in the spanwise direction
            - mat_struc   : matrix defining the nodes contained in the structures
            - field_u     : field of the streamwise velocity
            - field_v     : field of the wall-normal velocity
        * Classes:
            - structures  : class containing the structure information (read from py_bin.py_class.structures)
    .....................................................................................................................
    """
    def __init__(self,data_in={"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                               "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                               "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"umean.txt",
                               "urms_file":"SHAPrms.txt","sym_quad":True,"filvol":2.7e4,
                               "shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                               "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_Qstruc/",
                               "file":"P125_21pi_vu.$INDEX$.h5.Q","padding":15,"data_type":"float32","nsamples":200,
                               "SHAPrms_file":"SHAPrms.txt"}):
        """
        .................................................................................................................
        # __init__
        .................................................................................................................
        Function to initilize the shap structures.

        Parameters
        ----------
        data_in : dict, optional
            Data for initilizing the uv structure.
            The default is {"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                            "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                            "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"umean.txt",
                            "urms_file":"SHAPrms.txt","sym_quad":True,"filvol":2.7e4,
                            "shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                            "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_Qstruc/",
                            "file":"P125_21pi_vu.$INDEX$.h5.Q","padding":15,"data_type":"float32","nsamples:200",
                            "SHAPrms_file":"SHAPrms.txt"}.
            Data:
                - uvw_folder   : folder of the velocity flow fields
                - uvw_file     : file of the velocity flow fields
                - Hperc        : percolation index
                - index        : index of the field to read
                - dx           : downsampling in the streamwise direction
                - dy           : downsampling in the wall-normal direction
                - dz           : downsampling in the streamwise direction
                - L_x          : streamwise dimension of the channel
                - L_y          : wall-normal dimension of the channel
                - L_z          : spanwise dimension of the channel
                - rey          : friction Reynolds number
                - utau         : frictin velocity
                - padding      : padding of the fields
                - data_folder  : folder containing the data generated by the code
                - umean_file   : mean velocity file
                - urms_file    : rms velocity file
                - sym_quad     : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                                 of the structure
                - filvol       : volume for filtering the structures
                - shap_folder  : folder of the SHAP values
                - shap_file    : file of the SHAP values
                - folder       : folder to save the uv structures
                - file         : file to save the uv structures
                - padding      : padding of the fields
                - data_type    : type of float used for the data (float16, float32...)
                - nsamples     : number of samples used for the SHAP
                - SHAPrms_file : file for the RMS of the SHAP values
        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import dataset
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.shap_config import shap_config
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read data
        # ---------------------------------------------------------------------------------------------------------------
        self.uvw_folder   = str(data_in["uvw_folder"])
        self.uvw_file     = str(data_in["uvw_file"])
        self.Hperc        = float(data_in["Hperc"])
        self.index        = int(data_in["index"])
        self.down_x       = int(data_in["dx"])
        self.down_y       = int(data_in["dy"])
        self.L_x          = float(data_in["L_x"])
        self.L_y          = float(data_in["L_y"])
        self.rey          = float(data_in["rey"])
        self.utau         = float(data_in["utau"])
        self.padding      = int(data_in["padding"])
        self.data_folder  = str(data_in["data_folder"])
        self.umean_file   = str(data_in["umean_file"])
        self.urms_file    = str(data_in["urms_file"])
        self.sym_quad     = bool(data_in["sym_quad"])
        self.filvol       = float(data_in["filvol"])
        self.shap_folder  = str(data_in["shap_folder"])
        self.shap_file    = str(data_in["shap_file"])
        self.folder       = str(data_in["folder"])
        self.file         = str(data_in["file"])
        self.data_type    = str(data_in["data_type"])
        self.nsamples     = int(data_in["nsamples"])
        self.SHAPrms_file = str(data_in["SHAPrms_file"])

        # ---------------------------------------------------------------------------------------------------------------
        # Create the flow field (2D)
        # ---------------------------------------------------------------------------------------------------------------
        Data_flow = {"folder":self.uvw_folder,"file":self.uvw_file,"down_x":self.down_x,"down_y":self.down_y,
                     "L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,"utau":self.utau}
        flowfield = flow_field(data_in=Data_flow)
        flowfield.shape_tensor()
        flowfield.flow_grid()

        # ---------------------------------------------------------------------------------------------------------------
        # Store total area (legacy name)
        # ---------------------------------------------------------------------------------------------------------------
        self.voltot_plus = flowfield.voltot

        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the shape of the fields
        # ---------------------------------------------------------------------------------------------------------------
        self.shpy = flowfield.shpy
        self.shpx = flowfield.shpx

        # ---------------------------------------------------------------------------------------------------------------
        # Read the SHAP values (2D: u and v only). With padding=0 no cropping is needed.
        # ---------------------------------------------------------------------------------------------------------------
        data_shap   = {"shap_folder":self.shap_folder,"shap_file":self.shap_file,"uvw_folder":self.uvw_folder,
                       "uvw_file":self.uvw_file,"padding":self.padding,"dx":self.down_x,"dy":self.down_y,
                       "data_folder":self.data_folder,"umean_file":self.umean_file,
                       "unorm_file":"-","L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,
                       "utau":self.utau,"ngpu":0,"field_ini":0,"field_fin":0,"field_delta":0,
                       "model_folder":"-","model_read":"-","nfil":0,"stride":0,"activation":"-","kernel":0,
                       "pooling":0,"delta_pred":0,"nsamples":self.nsamples,"nsamples_max":self.nsamples,
                       "data_type":self.data_type,"error_file":"-","umax_file":"-","urmspred_file":"-",
                       "mean_norm":False,"tfrecord_folder":"-","nrep_field":0,"shap_batch":0,"repeat_exist":False,
                       "flag_model":False,"read_model":False}
        shap_model   = shap_config(data_in=data_shap)
        shap_data    = shap_model.read_shap(data_in = {"index":self.index})
        if self.padding > 0:
            self.field_u = shap_data["SHAP_u"][:, self.padding:-self.padding]
            self.field_v = shap_data["SHAP_v"][:, self.padding:-self.padding]
        else:
            self.field_u = shap_data["SHAP_u"]
            self.field_v = shap_data["SHAP_v"]
        
    def calculate_matstruc(self):
        """        
        .................................................................................................................
        # calculate_matstruc
        .................................................................................................................
        Function to calculate the matrix of the nodes belonging a structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Load the packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_functions.shaprms import read_rms
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the RMS of the velocity
        # ---------------------------------------------------------------------------------------------------------------
        data_read_SHAPrms = {"file":self.SHAPrms_file,"folder":self.data_folder}
        data_SHAPrms      = read_rms(data_in=data_read_SHAPrms)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the product of the velocty fluctuation and the product of the RMS velocity.
        # Then obtain the matrix containing the points belonging to the structures
        # ---------------------------------------------------------------------------------------------------------------
        # 2D PIV: u and v only; profiles are (shpy,) and broadcast along x with reshape(-1, 1).
        shap_xyz       = np.sqrt(self.field_u**2 + self.field_v**2)
        shap_rms       = np.sqrt(data_SHAPrms["SHAP_urms"]**2 + data_SHAPrms["SHAP_vrms"]**2).reshape(-1, 1)
        self.mat_struc = np.array(np.heaviside(shap_xyz - self.Hperc * shap_rms, 0), dtype='bool')
    
    def segment_struc(self):
        """       
        .................................................................................................................
        # segment_struc
        ................................................................................................................. 
        Function to segment the domain into the different structures

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        from py_bin.py_functions.read_velocity import read_velocity
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the velocity
        # ---------------------------------------------------------------------------------------------------------------
        data_read_vel  = {"folder":self.uvw_folder,"file":self.uvw_file,"index":self.index,
                          "dx":self.down_x,"dy":self.down_y,"shpx":self.shpx,"shpy":self.shpy,
                          "padding":0,"data_folder":self.data_folder,"umean_file":self.umean_file}
        data_vel       = read_velocity(data_in=data_read_vel)

        # ---------------------------------------------------------------------------------------------------------------
        # Create the structures and obtain the nodes of each structure (2D: no field_3)
        # ---------------------------------------------------------------------------------------------------------------
        data_struc      = {"mat_struc":self.mat_struc,"field_1":data_vel["uu"],"field_2":data_vel["vv"],
                           "field_3":np.zeros_like(data_vel["uu"]),"flag_sign":False,"uvw_folder":self.uvw_folder,
                           "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,
                           "L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,"utau":self.utau,
                           "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                           "shap_file":self.shap_file}
        self.structures = structures(data_in=data_struc)
        self.structures.separate_structures()
        self.structures.physicalproperties_structures()
        self.structures.detect_quadrant()
        self.structures.segmentation()
        self.structures.structure_u1u2()
        self.structures.structure_k123()
    
    def save_struc(self):
        """
        .................................................................................................................
        # save_struc
        .................................................................................................................
        Function to save the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Create the folder if not existing
        # ---------------------------------------------------------------------------------------------------------------
        try:
            print("Create folder",flush=True)
            os.mkdir(self.folder)
        except:
            print("Folder "+str(self.folder)+" is already created.",flush=True)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the file and save the information
        # ---------------------------------------------------------------------------------------------------------------
        hf = h5py.File(file_Q_ii,'w')
        hf.create_dataset('Qs',data=self.mat_struc)
        hf.create_dataset('Qs_event',data=self.structures.mat_event)
        hf.create_dataset('Qs_segment',data=self.structures.mat_segment)
        hf.create_dataset('Qs_segment_filtered',data=self.structures.mat_segment_filtered)
        hf.create_dataset('dim_x',data=self.structures.dim_x)
        hf.create_dataset('dim_z',data=self.structures.dim_z)
        hf.create_dataset('dim_y',data=self.structures.dim_y)
        hf.create_dataset('ymin',data=self.structures.ymin)
        hf.create_dataset('ymax',data=self.structures.ymax)
        hf.create_dataset('vol',data=self.structures.vol)
        hf.create_dataset('volbox',data=self.structures.boxvol)
        hf.create_dataset('cg_xbox',data=self.structures.cg_xbox)
        hf.create_dataset('cg_ybox',data=self.structures.cg_ybox)
        hf.create_dataset('cg_zbox',data=self.structures.cg_zbox)
        hf.create_dataset('cg_x',data=self.structures.cg_x)
        hf.create_dataset('cg_y',data=self.structures.cg_y)
        hf.create_dataset('cg_z',data=self.structures.cg_z)
        hf.create_dataset('event',data=self.structures.event)
        hf.create_dataset('uv_uvtot',data=self.structures.u1u2)
        hf.create_dataset('k_ktot',data=self.structures.k123)
        try:
            hf.create_dataset('shap',data=self.shap)
        except:
            pass
        hf.close()
        
    def read_struc(self):
        """
        .................................................................................................................
        # read_struc
        .................................................................................................................
        Function to read the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        print('Reading: '+file_Q_ii,flush=True)
        
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the file with the saved information
        # ---------------------------------------------------------------------------------------------------------------
        file           = h5py.File(file_Q_ii,'r')
        try:
            self.mat_struc = np.array(file['Qs'])
        except:
            self.mat_struc = np.heaviside(np.array(file['Qs_segment']),0)
            print("File do not contain the matrix Qs",flush=True)
        # ---------------------------------------------------------------------------------------------------------------
        # Define the structure class
        # ---------------------------------------------------------------------------------------------------------------
        data_struc      = {"mat_struc":self.mat_struc,"field_1":self.field_u,"field_2":self.field_v,
                           "field_3":np.zeros_like(self.field_u),"flag_sign":True,"uvw_folder":self.uvw_folder,
                           "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,
                           "L_x":self.L_x,"L_y":self.L_y,"rey":self.rey,"utau":self.utau,
                           "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                           "shap_file":self.shap_file}
        self.structures = structures(data_in=data_struc)
        
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the rest of the data
        # ---------------------------------------------------------------------------------------------------------------
        try:
            self.structures.mat_event            = np.array(file['Qs_event'])
        except:
            print("Event type does not exist",flush=True)
        try:
            self.structures.mat_segment          = np.array(file['Qs_segment'])
        except:
            print("Segmentation matrix type does not exist",flush=True)
        try:
            self.structures.dim_x                = np.array(file['dim_x'])
        except:
            print("Dimension of the structures in the streamwise direction are not provided",flush=True)
        try:
            self.structures.dim_y                = np.array(file['dim_y'])
        except:
            print("Dimension of the structures in the wall-normal direction are not provided",flush=True)
        try:
            self.structures.dim_z                = np.array(file['dim_z'])
        except:
            print("Dimension of the structures in the spanwise direction are not provided",flush=True)
        try:
            self.structures.ymin                 = np.array(file['ymin'])
        except:
            print("Minimum wall-normal distance of the structures is not provided",flush=True)
        try:
            self.structures.ymax                 = np.array(file['ymax'])
        except:
            print("Maximum wall-normal distance of the structures is not provided",flush=True)
        try:
            self.structures.vol                  = np.array(file['vol'])
        except:
            print("Volume of the structures is not provided",flush=True)
        try:
            self.structures.boxvol               = np.array(file['volbox'])
        except:
            print("Volume of the box of the structures is not provided",flush=True)
        try:
            self.structures.cg_xbox              = np.array(file['cg_xbox'])
        except:
            print("Center of gravity in the streamwise direction of the box of the structures is not provided",
                  flush=True)
        try:
            self.structures.cg_ybox              = np.array(file['cg_ybox'])
        except:
            print("Center of gravity in the wall-normal direction of the box of the structures is not provided",
                  flush=True)
        try:
            self.structures.cg_zbox              = np.array(file['cg_zbox'])
        except:
            print("Center of gravity in the spanwise direction of the box of the structures is not provided",
                  flush=True)
        try:
            self.structures.cg_x                 = np.array(file['cg_x'])
        except:
            print("Center of gravity in the streamwise direction of the structure is not provided",
                  flush=True)
        try:
            self.structures.cg_y                 = np.array(file['cg_y'])
        except:
            print("Center of gravity in the streamwise direction of the structure is not provided",
                  flush=True)
        try:
            self.structures.cg_z                 = np.array(file['cg_z'])
        except:
            print("Center of gravity in the streamwise direction of the structure is not provided",
                  flush=True)
        try:
            self.structures.event                = np.array(file['event'])
        except:
            print("Type of event of the structure is not provided",flush=True)
        try:
            self.structures.u1u2                 = np.array(file['uv_uvtot'])
        except:
            print("Reynolds stress of the structure is not provided",flush=True)
        try:
            self.structures.k_ktot               = np.array(file['k_ktot'])
        except:
            print("Kinetic energy of the structure is not provided",flush=True)
        try:
            self.shap                            = np.array(file['shap'])
        except:
            print("SHAP value of the structure is not provided",flush=True)
        try:
            self.structures.mat_segment_filtered = np.array(file['Qs_segment_filtered'])
        except:
            self.structures.mat_segment_filtered = np.zeros_like(self.structures.mat_segment)
            try:
                index_struc2 = 1
                filt_index   = []
                for index_struc in np.arange(len(self.structures.vol)):
                    if self.structures.vol[index_struc] >= self.filvol:
                        filt_index.append(index_struc)
                        self.structures.mat_segment_filtered[self.structures.mat_segment==
                                                             index_struc+1] = index_struc2
                        index_struc2 += 1
                self.structures.filt_index = np.array(filt_index,dtype="int")
            except:
                print("Filtered segmentation matrix type does not exist, using complete set",flush=True)
        # ---------------------------------------------------------------------------------------------------------------
        # Read the rest of the data
        # ---------------------------------------------------------------------------------------------------------------
            
    def reconstruct_fromprevious(self, data_in=None):
        raise NotImplementedError("3D legacy helper, not supported in 2D PIV.")

    def add_SHAP(self,data_in={"nsamples":1}):
        """
        .................................................................................................................
        # add_SHAP
        .................................................................................................................
        Function for adding the total SHAP value of each structure to the structures file
        
        Parameters
        ----------
        data_in : dict, optional
            Name of the folder and file of the file of the previous data.
            The default is {"nsamples":1}.
            Data:
                - nsamples : number of samples of the shap
        
        Returns
        -------
        None.
        
        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.shap_config import shap_config
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        nsamples = int(data_in["nsamples"])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the SHAP value of the structure and save it
        # ---------------------------------------------------------------------------------------------------------------
        # 2D PIV: SHAP tensor is (shpy, shpx, 2) with u and v only
        shap_data        = np.zeros((self.shpy, self.shpx, 2))
        shap_data[:,:,0] = self.field_u
        shap_data[:,:,1] = self.field_v
        
        # ---------------------------------------------------------------------------------------------------------------
        # For every structure sum all the norms of the SHAP values of the nodes of the structure
        #     - nn : index of the structure
        #     - nodes_nn : indices of the nodes of the structure nn
        # ---------------------------------------------------------------------------------------------------------------
        max_struc = int(np.max(self.structures.mat_segment))
        self.shap = np.zeros((max_struc,))
        for nn  in np.arange(max_struc-1):
            nodes_nn       = np.where(self.structures.mat_segment==nn+1)
            self.shap[nn] += np.linalg.norm(shap_data[nodes_nn])
        
        
