# -*- coding: utf-8 -*-
"""
-------------------------------------------------------------------------------------------------------------------------
shap_uvw_structures.py
-------------------------------------------------------------------------------------------------------------------------
Created on Wed Apr  3 15:02:00 2024

@author: Andres Cremades Botella

File to define the shap structures percolating with the different components
:
    Class:
        - shap_structure : Class of the SHAP value coherent structures.
"""
# -----------------------------------------------------------------------------------------------------------------------
# Import packages for all functions
# -----------------------------------------------------------------------------------------------------------------------
import os
import numpy as np
import h5py
from py_bin.py_class.flow_field import flow_field
import sys

# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------
# Define functions
# -----------------------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------

class shap_structure():
    """
    .....................................................................................................................
    # shap_structure: Class of the SHAP value coherent structures.
        * Functions:
            - __init__ : initialization function
            - calculate_matstruc : calculate the matrix containing the nodes included in the transverse Reynolds stress
                                   structures.
            - segment_struc      : calculates the segmentation of the domain based on the transverse Reynolds stress
                                   structures.
            - save_struc         : function to save the structures
            - read_struc         : function to read the structures
        * Variables:
            - uvw_folder  : folder of the velocity flow fields
            - uvw_file    : file of the velocity flow fields
            - Hperc       : percolation index
            - index       : index of the field to read
            - dx          : downsampling in the streamwise direction
            - dy          : downsampling in the wall-normal direction
            - dz          : downsampling in the streamwise direction
            - L_x         : streamwise dimension of the channel
            - L_y         : wall-normal dimension of the channel
            - L_z         : spanwise dimension of the channel
            - rey         : friction Reynolds number
            - utau        : frictin velocity
            - padding     : padding of the fields
            - data_folder : folder containing the data generated by the code
            - umean_file  : mean velocity file
            - urms_file   : rms velocity file
            - sym_quad    : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                            of the structure
            - filvol      : volume for filtering the structures
            - shap_folder : folder of the SHAP values
            - shap_file   : file of the SHAP values
            - folder      : folder to save the uv structures
            - file        : file to save the uv structures
            - shpy        : shape of the tensors in the wall-normal direction
            - shpx        : shape of the tensors in the streamwise direction
            - shpz        : shape of the tensors in the spanwise direction
            - mat_struc   : matrix defining the nodes contained in the structures
            - field_u     : field of the streamwise velocity
            - field_v     : field of the wall-normal velocity
        * Classes:
            - structures  : class containing the structure information (read from py_bin.py_class.structures)
    .....................................................................................................................
    """
    def __init__(self,data_in={"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                               "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                               "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"umean.txt",
                               "urms_file":"SHAPrms.txt","sym_quad":True,"filvol":2.7e4,
                               "shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                               "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_Qstruc/",
                               "file":"P125_21pi_vu.$INDEX$.h5.Q","padding":15,"data_type":"float32","nsamples":200,
                               "SHAPrms_file":"SHAPrms.txt","SHAPmean_file":"SHAPmean.txt"}):
        """
        .................................................................................................................
        # __init__
        .................................................................................................................
        Function to initilize the shap structures.

        Parameters
        ----------
        data_in : dict, optional
            Data for initilizing the uv structure.
            The default is {"uvw_folder":"../../P125_21pi_vu/","uvw_file":"P125_21pi_vu.$INDEX$.h5.uvw","Hperc":1.75,
                            "index":7000,"dx":1,"dy":1,"dz":1,"L_x":2*np.pi,"L_y":1,"L_z":np.pi,"rey":125,
                            "utau":0.060523258443963,"padding":15,"data_folder":"Data","umean_file":"umean.txt",
                            "urms_file":"SHAPrms.txt","sym_quad":True,"filvol":2.7e4,
                            "shap_folder":"../../P125_21pi_vu_SHAP_UnetXAI_gradient/",
                            "shap_file":"P125_21pi_vu.$INDEX$.h5.shap","folder":"../../P125_21pi_vu_Qstruc/",
                            "file":"P125_21pi_vu.$INDEX$.h5.Q","padding":15,"data_type":"float32","nsamples:200",
                            "SHAPrms_file":"SHAPrms.txt","SHAPmean_file":"SHAPmean.txt"}.
            Data: 
                - uvw_folder    : folder of the velocity flow fields
                - uvw_file      : file of the velocity flow fields
                - Hperc         : percolation index
                - index         : index of the field to read
                - dx            : downsampling in the streamwise direction
                - dy            : downsampling in the wall-normal direction
                - dz            : downsampling in the streamwise direction
                - L_x           : streamwise dimension of the channel
                - L_y           : wall-normal dimension of the channel
                - L_z           : spanwise dimension of the channel
                - rey           : friction Reynolds number
                - utau          : frictin velocity
                - padding       : padding of the fields
                - data_folder   : folder containing the data generated by the code
                - umean_file    : mean velocity file
                - urms_file     : rms velocity file
                - sym_quad      : flag fo using the symmetry of the direction 2 of the field for calculating the quadrant
                                  of the structure
                - filvol        : volume for filtering the structures
                - shap_folder   : folder of the SHAP values
                - shap_file     : file of the SHAP values
                - folder        : folder to save the uv structures
                - file          : file to save the uv structures
                - padding       : padding of the fields
                - data_type     : type of float used for the data (float16, float32...)
                - nsamples      : number of samples used for the SHAP
                - SHAPrms_file  : file for the RMS of the SHAP values
                - SHAPmean_file : file for the mean of the SHAP values
        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import dataset
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.shap_config import shap_config
        from py_bin.py_functions.shapmean import read_SHAPmean
        from py_bin.py_functions.read_velocity import read_velocity
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read data
        # ---------------------------------------------------------------------------------------------------------------
        self.uvw_folder    = str(data_in["uvw_folder"])  # folder of the flow field data
        self.uvw_file      = str(data_in["uvw_file"])    # file of the flow field
        Hperc              = float(data_in["Hperc"])     # percolation index
        self.index         = int(data_in["index"])       # index of the field to read
        self.down_x        = int(data_in["dx"])          # downsampling in the x direction
        self.down_y        = int(data_in["dy"])          # downsampling in the y direction
        self.down_z        = int(data_in["dz"])          # downsampling in the z direction
        self.L_x           = float(data_in["L_x"])       # dimension in the x direction
        self.L_y           = float(data_in["L_y"])       # dimension in the y direction
        self.L_z           = float(data_in["L_z"])       # dimension in the z direction
        self.rey           = float(data_in["rey"])       # friction reynolds number
        self.utau          = float(data_in["utau"])      # friction velocity
        self.padding       = int(data_in["padding"])     # padding of the fields
        self.data_folder   = str(data_in["data_folder"]) # folder to store the data generated by the code
        self.umean_file    = str(data_in["umean_file"])  # file of the mean velocity
        self.urms_file     = str(data_in["urms_file"])   # file of the rms velocity
        self.sym_quad      = bool(data_in["sym_quad"])   # flag for using the simmetry on direction 2 for quadrants
        self.filvol        = float(data_in["filvol"])    # volume for filtering the structures
        self.shap_folder   = str(data_in["shap_folder"]) # folder of the SHAP values
        self.shap_file     = str(data_in["shap_file"])   # file of the SHAP values
        self.folder        = str(data_in["folder"])      # folder to save the uv structures
        self.file          = str(data_in["file"])        # file to save the uv structures
        self.padding       = int(data_in["padding"])
        self.data_type     = str(data_in["data_type"])
        self.nsamples      = int(data_in["nsamples"])
        self.SHAPrms_file  = str(data_in["SHAPrms_file"])
        self.SHAPmean_file = str(data_in["SHAPmean_file"])
        self.Hpercu        = Hperc
        self.Hpercv        = Hperc
        self.Hpercw        = Hperc
                
        # ---------------------------------------------------------------------------------------------------------------
        # Create the flow field
        # ---------------------------------------------------------------------------------------------------------------
        Data_flow = {"folder":self.uvw_folder,"file":self.uvw_file,"down_x":self.down_x,"down_y":self.down_y,
                     "down_z":self.down_z,"L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau}
        flowfield = flow_field(data_in=Data_flow)
        flowfield.shape_tensor()
        flowfield.flow_grid()
        
        # ---------------------------------------------------------------------------------------------------------------
        # Store total volume
        # ---------------------------------------------------------------------------------------------------------------
        self.voltot_plus = flowfield.voltot_plus
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the shape of the fields
        # ---------------------------------------------------------------------------------------------------------------
        self.shpy = flowfield.shpy   # Shape in y
        self.shpz = flowfield.shpz   # Shape in z
        self.shpx = flowfield.shpx   # Shape in x
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the mean shap
        # ---------------------------------------------------------------------------------------------------------------
        try:
            data_SHAPmean  = read_SHAPmean(data_in={"folder":self.data_folder,"file":self.SHAPmean_file,
                                                    "dy":self.down_y})
            SHAP_umean     = data_SHAPmean["SHAP_umean"]
            SHAP_vmean     = data_SHAPmean["SHAP_vmean"]
            SHAP_wmean     = data_SHAPmean["SHAP_wmean"]
        except:
            print("SHAP structures require mean velocity file. Breaking calculation...",flush=True)
            sys.exit()
            
        # ---------------------------------------------------------------------------------------------------------------
        # Read the shap
        # ---------------------------------------------------------------------------------------------------------------
        data_shap   = {"shap_folder":self.shap_folder,"shap_file":self.shap_file,"uvw_folder":self.uvw_folder,
                       "uvw_file":self.uvw_file,"padding":self.padding,"dx":self.down_x,"dy":self.down_y,
                       "dz":self.down_z,"data_folder":self.data_folder,"umean_file":self.umean_file,
                       "unorm_file":"-","L_x":self.L_x,"L_z":self.L_z,"L_y":self.L_y,"rey":self.rey,
                       "utau":self.utau,"ngpu":0,"field_ini":0,"field_fin":0,"field_delta":0,
                       "model_folder":"-","model_read":"-","nfil":0,"stride":0,"activation":"-","kernel":0,
                       "pooling":0,"delta_pred":0,"nsamples":self.nsamples,"nsamples_max":self.nsamples,
                       "data_type":self.data_type,"error_file":"-","umax_file":"-","urmspred_file":"-",
                       "mean_norm":False,"tfrecord_folder":"-","nrep_field":0,"shap_batch":0,"repeat_exist":False,
                       "flag_model":False}
        shap_model   = shap_config(data_in=data_shap)
        shap_data    = shap_model.read_shap(data_in = {"index":self.index})
        self.field_u = shap_data["SHAP_u"][:,self.padding:-self.padding, 
                                           self.padding:-self.padding]-SHAP_umean.reshape(-1,1,1)
        self.field_v = shap_data["SHAP_v"][:,self.padding:-self.padding,
                                           self.padding:-self.padding]-SHAP_vmean.reshape(-1,1,1)
        self.field_w = shap_data["SHAP_w"][:,self.padding:-self.padding,
                                           self.padding:-self.padding]-SHAP_wmean.reshape(-1,1,1)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the velocity
        # ---------------------------------------------------------------------------------------------------------------
        data_read_vel  = {"folder":self.uvw_folder,"file":self.uvw_file,"index":self.index,
                          "dx":self.down_x,"dy":self.down_y,"dz":self.down_z,"shpx":self.shpx,"shpy":self.shpy,
                          "shpz":self.shpz,"padding":0,"data_folder":self.data_folder,"umean_file":self.umean_file}
        data_vel       = read_velocity(data_in=data_read_vel)
        self.vel_u     = data_vel["uu"]
        self.vel_v     = data_vel["vv"]
        self.vel_w     = data_vel["ww"]
        
    def calculate_matstruc(self):
        """        
        .................................................................................................................
        # calculate_matstruc
        .................................................................................................................
        Function to calculate the matrix of the nodes belonging a structure a matrix is calculated for each component

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Load the packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_functions.shaprms import read_rms
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the RMS of the velocity
        # ---------------------------------------------------------------------------------------------------------------
        data_read_SHAPrms = {"file":self.SHAPrms_file,"folder":self.data_folder}
        data_SHAPrms      = read_rms(data_in=data_read_SHAPrms)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the product of the velocty fluctuation and the product of the RMS velocity.
        # Then obtain the matrix containing the points belonging to the structures
        # ---------------------------------------------------------------------------------------------------------------
        self.mat_struc_u = np.array(np.heaviside(-self.field_u-self.Hpercu*
                                                 data_SHAPrms["SHAP_urms"].reshape(-1,1,1),0),dtype='bool')
        self.mat_struc_v = np.array(np.heaviside(abs(self.field_v)-self.Hpercv*
                                                 data_SHAPrms["SHAP_vrms"].reshape(-1,1,1),0),dtype='bool')
        self.mat_struc_w = np.array(np.heaviside(-self.field_w-self.Hpercw*
                                                 data_SHAPrms["SHAP_wrms"].reshape(-1,1,1),0),dtype='bool')
    
    def segment_struc(self):
        """       
        .................................................................................................................
        # segment_struc
        ................................................................................................................. 
        Function to segment the domain into the different structures

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the structures and obtain the nodes of each structure
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_u      = {"mat_struc":self.mat_struc_u,"field_1":self.vel_u,"field_2":self.vel_v,
                             "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_u = structures(data_in=data_struc_u)
        self.structures_u.separate_structures()
        self.structures_u.physicalproperties_structures()
        self.structures_u.detect_quadrant()
        self.structures_u.segmentation()
        self.structures_u.structure_u1u2()
        self.structures_u.structure_k123()
        data_struc_v      = {"mat_struc":self.mat_struc_v,"field_1":self.vel_u,"field_2":self.vel_v,
                             "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_v = structures(data_in=data_struc_v)
        self.structures_v.separate_structures()
        self.structures_v.physicalproperties_structures()
        self.structures_v.detect_quadrant()
        self.structures_v.segmentation()
        self.structures_v.structure_u1u2()
        self.structures_v.structure_k123()
        data_struc_w      = {"mat_struc":self.mat_struc_w,"field_1":self.vel_u,"field_2":self.vel_v,
                             "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_w = structures(data_in=data_struc_w)
        self.structures_w.separate_structures()
        self.structures_w.physicalproperties_structures()
        self.structures_w.detect_quadrant()
        self.structures_w.segmentation()
        self.structures_w.structure_u1u2()
        self.structures_w.structure_k123()
    
    def save_struc(self):
        """
        .................................................................................................................
        # save_struc
        .................................................................................................................
        Function to save the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Create the folder if not existing
        # ---------------------------------------------------------------------------------------------------------------
        try:
            print("Create folder",flush=True)
            os.mkdir(self.folder)
        except:
            print("Folder "+str(self.folder)+" is already created.",flush=True)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the file and save the information
        # ---------------------------------------------------------------------------------------------------------------
        hf = h5py.File(file_Q_ii,'w')
        hf.create_dataset('Qs_u',data=self.mat_struc_u)
        hf.create_dataset('Qs_event_u',data=self.structures_u.mat_event)
        hf.create_dataset('Qs_segment_u',data=self.structures_u.mat_segment)
        hf.create_dataset('Qs_segment_filtered_u',data=self.structures_u.mat_segment_filtered)
        hf.create_dataset('dim_x_u',data=self.structures_u.dim_x)
        hf.create_dataset('dim_z_u',data=self.structures_u.dim_z)
        hf.create_dataset('dim_y_u',data=self.structures_u.dim_y)
        hf.create_dataset('ymin_u',data=self.structures_u.ymin)
        hf.create_dataset('ymax_u',data=self.structures_u.ymax)
        hf.create_dataset('vol_u',data=self.structures_u.vol)
        hf.create_dataset('volbox_u',data=self.structures_u.boxvol)
        hf.create_dataset('cg_xbox_u',data=self.structures_u.cg_xbox)
        hf.create_dataset('cg_ybox_u',data=self.structures_u.cg_ybox)
        hf.create_dataset('cg_zbox_u',data=self.structures_u.cg_zbox)
        hf.create_dataset('cg_x_u',data=self.structures_u.cg_x)
        hf.create_dataset('cg_y_u',data=self.structures_u.cg_y)
        hf.create_dataset('cg_z_u',data=self.structures_u.cg_z)
        hf.create_dataset('event_u',data=self.structures_u.event)
        hf.create_dataset('uv_uvtot_u',data=self.structures_u.u1u2)
        hf.create_dataset('k_ktot_u',data=self.structures_u.k123)
        try:
            hf.create_dataset('shap_u',data=self.shap_u)
        except:
            pass
        
        hf.create_dataset('Qs_v',data=self.mat_struc_v)
        hf.create_dataset('Qs_event_v',data=self.structures_v.mat_event)
        hf.create_dataset('Qs_segment_v',data=self.structures_v.mat_segment)
        hf.create_dataset('Qs_segment_filtered_v',data=self.structures_v.mat_segment_filtered)
        hf.create_dataset('dim_x_v',data=self.structures_v.dim_x)
        hf.create_dataset('dim_z_v',data=self.structures_v.dim_z)
        hf.create_dataset('dim_y_v',data=self.structures_v.dim_y)
        hf.create_dataset('ymin_v',data=self.structures_v.ymin)
        hf.create_dataset('ymax_v',data=self.structures_v.ymax)
        hf.create_dataset('vol_v',data=self.structures_v.vol)
        hf.create_dataset('volbox_v',data=self.structures_v.boxvol)
        hf.create_dataset('cg_xbox_v',data=self.structures_v.cg_xbox)
        hf.create_dataset('cg_ybox_v',data=self.structures_v.cg_ybox)
        hf.create_dataset('cg_zbox_v',data=self.structures_v.cg_zbox)
        hf.create_dataset('cg_x_v',data=self.structures_v.cg_x)
        hf.create_dataset('cg_y_v',data=self.structures_v.cg_y)
        hf.create_dataset('cg_z_v',data=self.structures_v.cg_z)
        hf.create_dataset('event_v',data=self.structures_v.event)
        hf.create_dataset('uv_uvtot_v',data=self.structures_v.u1u2)
        hf.create_dataset('k_ktot_v',data=self.structures_v.k123)
        try:
            hf.create_dataset('shap_v',data=self.shap_v)
        except:
            pass
        
        hf.create_dataset('Qs_w',data=self.mat_struc_w)
        hf.create_dataset('Qs_event_w',data=self.structures_w.mat_event)
        hf.create_dataset('Qs_segment_w',data=self.structures_w.mat_segment)
        hf.create_dataset('Qs_segment_filtered_w',data=self.structures_w.mat_segment_filtered)
        hf.create_dataset('dim_x_w',data=self.structures_w.dim_x)
        hf.create_dataset('dim_z_w',data=self.structures_w.dim_z)
        hf.create_dataset('dim_y_w',data=self.structures_w.dim_y)
        hf.create_dataset('ymin_w',data=self.structures_w.ymin)
        hf.create_dataset('ymax_w',data=self.structures_w.ymax)
        hf.create_dataset('vol_w',data=self.structures_w.vol)
        hf.create_dataset('volbox_w',data=self.structures_w.boxvol)
        hf.create_dataset('cg_xbox_w',data=self.structures_w.cg_xbox)
        hf.create_dataset('cg_ybox_w',data=self.structures_w.cg_ybox)
        hf.create_dataset('cg_zbox_w',data=self.structures_w.cg_zbox)
        hf.create_dataset('cg_x_w',data=self.structures_w.cg_x)
        hf.create_dataset('cg_y_w',data=self.structures_w.cg_y)
        hf.create_dataset('cg_z_w',data=self.structures_w.cg_z)
        hf.create_dataset('event_w',data=self.structures_w.event)
        hf.create_dataset('uv_uvtot_w',data=self.structures_w.u1u2)
        hf.create_dataset('k_ktot_w',data=self.structures_w.k123)
        try:
            hf.create_dataset('shap_w',data=self.shap_w)
        except:
            pass
        hf.close()
        
    def read_struc(self):
        """
        .................................................................................................................
        # read_struc
        .................................................................................................................
        Function to read the parameters of the structure

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        print('Reading: '+file_Q_ii,flush=True)
        
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the file with the saved information
        # ---------------------------------------------------------------------------------------------------------------
        file             = h5py.File(file_Q_ii,'r')
        self.mat_struc_u = np.array(file['Qs_u'])
        self.mat_struc_v = np.array(file['Qs_v'])
        self.mat_struc_w = np.array(file['Qs_w'])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Define the structure class
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_u      = {"mat_struc":self.mat_struc_u,"field_1":self.field_u,"field_2":self.field_v,
                             "field_3":self.field_w,"flag_sign":True,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_u = structures(data_in=data_struc_u)
        data_struc_v      = {"mat_struc":self.mat_struc_v,"field_1":self.field_u,"field_2":self.field_v,
                             "field_3":self.field_w,"flag_sign":True,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_v = structures(data_in=data_struc_v)
        data_struc_w      = {"mat_struc":self.mat_struc_w,"field_1":self.field_u,"field_2":self.field_v,
                             "field_3":self.field_w,"flag_sign":True,"uvw_folder":self.uvw_folder,
                             "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                             "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                             "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                             "shap_file":self.shap_file}
        self.structures_w = structures(data_in=data_struc_w)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the rest of the data
        # ---------------------------------------------------------------------------------------------------------------
        self.structures_u.mat_event            = np.array(file['Qs_event_u'])
        self.structures_u.mat_segment          = np.array(file['Qs_segment_u'])
        self.structures_u.mat_segment_filtered = np.array(file['Qs_segment_filtered_u'])
        self.structures_u.dim_x                = np.array(file['dim_x_u'])
        self.structures_u.dim_y                = np.array(file['dim_y_u'])
        self.structures_u.dim_z                = np.array(file['dim_z_u'])
        self.structures_u.ymin                 = np.array(file['ymin_u'])
        self.structures_u.ymax                 = np.array(file['ymax_u'])
        self.structures_u.vol                  = np.array(file['vol_u'])
        self.structures_u.boxvol               = np.array(file['volbox_u'])
        self.structures_u.cg_xbox              = np.array(file['cg_xbox_u'])
        self.structures_u.cg_ybox              = np.array(file['cg_ybox_u'])
        self.structures_u.cg_zbox              = np.array(file['cg_zbox_u'])
        self.structures_u.cg_x                 = np.array(file['cg_x_u'])
        self.structures_u.cg_y                 = np.array(file['cg_y_u'])
        self.structures_u.cg_z                 = np.array(file['cg_z_u'])
        self.structures_u.event                = np.array(file['event_u'])
        self.structures_u.u1u2                 = np.array(file['uv_uvtot_u'])
        self.structures_u.k_ktot               = np.array(file['k_ktot_u'])
        try:
            self.shap_u                        = np.array(file['shap_u'])
        except:
            pass
        
        self.structures_v.mat_event            = np.array(file['Qs_event_v'])
        self.structures_v.mat_segment          = np.array(file['Qs_segment_v'])
        self.structures_v.mat_segment_filtered = np.array(file['Qs_segment_filtered_v'])
        self.structures_v.dim_x                = np.array(file['dim_x_v'])
        self.structures_v.dim_y                = np.array(file['dim_y_v'])
        self.structures_v.dim_z                = np.array(file['dim_z_v'])
        self.structures_v.ymin                 = np.array(file['ymin_v'])
        self.structures_v.ymax                 = np.array(file['ymax_v'])
        self.structures_v.vol                  = np.array(file['vol_v'])
        self.structures_v.boxvol               = np.array(file['volbox_v'])
        self.structures_v.cg_xbox              = np.array(file['cg_xbox_v'])
        self.structures_v.cg_ybox              = np.array(file['cg_ybox_v'])
        self.structures_v.cg_zbox              = np.array(file['cg_zbox_v'])
        self.structures_v.cg_x                 = np.array(file['cg_x_v'])
        self.structures_v.cg_y                 = np.array(file['cg_y_v'])
        self.structures_v.cg_z                 = np.array(file['cg_z_v'])
        self.structures_v.event                = np.array(file['event_v'])
        self.structures_v.u1u2                 = np.array(file['uv_uvtot_v'])
        self.structures_v.k_ktot               = np.array(file['k_ktot_v'])
        try:
            self.shap_v                        = np.array(file['shap_v'])
        except:
            pass
        
        self.structures_w.mat_event            = np.array(file['Qs_event_w'])
        self.structures_w.mat_segment          = np.array(file['Qs_segment_w'])
        self.structures_w.mat_segment_filtered = np.array(file['Qs_segment_filtered_w'])
        self.structures_w.dim_x                = np.array(file['dim_x_w'])
        self.structures_w.dim_y                = np.array(file['dim_y_w'])
        self.structures_w.dim_z                = np.array(file['dim_z_w'])
        self.structures_w.ymin                 = np.array(file['ymin_w'])
        self.structures_w.ymax                 = np.array(file['ymax_w'])
        self.structures_w.vol                  = np.array(file['vol_w'])
        self.structures_w.boxvol               = np.array(file['volbox_w'])
        self.structures_w.cg_xbox              = np.array(file['cg_xbox_w'])
        self.structures_w.cg_ybox              = np.array(file['cg_ybox_w'])
        self.structures_w.cg_zbox              = np.array(file['cg_zbox_w'])
        self.structures_w.cg_x                 = np.array(file['cg_x_w'])
        self.structures_w.cg_y                 = np.array(file['cg_y_w'])
        self.structures_w.cg_z                 = np.array(file['cg_z_w'])
        self.structures_w.event                = np.array(file['event_w'])
        self.structures_w.u1u2                 = np.array(file['uv_uvtot_w'])
        self.structures_w.k_ktot               = np.array(file['k_ktot_w'])
        try:
            self.shap_w                        = np.array(file['shap_w'])
        except:
            pass
 
          
    def add_SHAP(self,data_in={"nsamples":1}):
        """
        .................................................................................................................
        # add_SHAP
        .................................................................................................................
        Function for adding the total SHAP value of each structure to the structures file
        
        Parameters
        ----------
        data_in : dict, optional
            Name of the folder and file of the file of the previous data.
            The default is {"nsamples":1}.
            Data:
                - nsamples : number of samples of the shap
        
        Returns
        -------
        None.
        
        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.shap_config import shap_config
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        nsamples = int(data_in["nsamples"])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the SHAP value of the structure and save it
        # ---------------------------------------------------------------------------------------------------------------
        shap_data          = np.zeros((self.shpy,self.shpz,self.shpx,3))
        shap_data[:,:,:,0] = self.field_u
        shap_data[:,:,:,1] = self.field_v 
        shap_data[:,:,:,2] = self.field_w
        
        # ---------------------------------------------------------------------------------------------------------------
        # For every structure sum all the norms of the SHAP values of the nodes of the structure
        #     - nn : index of the structure
        #     - nodes_nn : indices of the nodes of the structure nn
        # ---------------------------------------------------------------------------------------------------------------
        max_struc_u = int(np.max(self.structures_u.mat_segment))
        self.shap_u = np.zeros((max_struc_u,))
        for nn  in np.arange(max_struc_u-1):
            nodes_nn         = np.where(self.structures_u.mat_segment==nn+1)
            self.shap_u[nn] += np.linalg.norm(shap_data[nodes_nn])
        
        max_struc_v = int(np.max(self.structures_v.mat_segment))
        self.shap_v = np.zeros((max_struc_v,))
        for nn  in np.arange(max_struc_v-1):
            nodes_nn         = np.where(self.structures_v.mat_segment==nn+1)
            self.shap_v[nn] += np.linalg.norm(shap_data[nodes_nn])
        
        max_struc_w = int(np.max(self.structures_w.mat_segment))
        self.shap_w = np.zeros((max_struc_w,))
        for nn  in np.arange(max_struc_w-1):
            nodes_nn         = np.where(self.structures_w.mat_segment==nn+1)
            self.shap_w[nn] += np.linalg.norm(shap_data[nodes_nn])
        
         
    def structure_Quadrant(self,data_in={"nsamples":1}):
        """
        .................................................................................................................
        # structure_Quadrant
        .................................................................................................................
        Function for clasifying the areas of the domain by type of structure. The following clasification is generated:
            - Q100 : Structures belonging only to the classification in shap_u
            - Q001 : Structures belonging only to the classification in shap_w
            - Q010 : Structures belonging only to the classification in negative shap_v
            - Q020 : Structures belonging only to the classification in possitive shap_v
            - Q101 : Structures belonging to shap_u+shap_w
            - Q110 : Structures belonging to shap_u+negative shap_v
            - Q120 : Structures belonging to shap_u+possitive shap_v
            - Q011 : Structures belonging to negative shap_v+shap_w
            - Q021 : Structures belonging to possitive shap_v+shap_w
            - Q111 : Structures belonging to shap_u+negative shap_v+shap_w
            - Q121 : Structures belonging to shap_u+possitive shap_u+shap_w
        
        Parameters
        ----------
        data_in : dict, optional
            Name of the folder and file of the file of the previous data.
            The default is {"nsamples":1}.
            Data:
                - nsamples : number of samples of the shap
        Returns
        -------
        None.
        
        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        from py_bin.py_class.shap_config import shap_config
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        nsamples = int(data_in["nsamples"])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Assign a value to the points 
        # ---------------------------------------------------------------------------------------------------------------
        mat_u  = self.mat_struc_u
        mat_v  = self.mat_struc_v*2
        mat_w  = self.mat_struc_w*4
        mattot = mat_u+mat_v+mat_w
        
        # ---------------------------------------------------------------------------------------------------------------
        # Define the matrices
        # ---------------------------------------------------------------------------------------------------------------
        self.mat_struc_Q100 = np.zeros_like(mat_u)
        self.mat_struc_Q001 = np.zeros_like(mat_u)
        self.mat_struc_Q010 = np.zeros_like(mat_u)
        self.mat_struc_Q020 = np.zeros_like(mat_u)
        self.mat_struc_Q101 = np.zeros_like(mat_u)
        self.mat_struc_Q110 = np.zeros_like(mat_u)
        self.mat_struc_Q120 = np.zeros_like(mat_u)
        self.mat_struc_Q011 = np.zeros_like(mat_u)
        self.mat_struc_Q021 = np.zeros_like(mat_u)
        self.mat_struc_Q111 = np.zeros_like(mat_u)
        self.mat_struc_Q121 = np.zeros_like(mat_u)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Define structures clasified by type
        # ---------------------------------------------------------------------------------------------------------------
        self.mat_struc_Q100[mattot==1]      = 1
        self.mat_struc_Q001[mattot==4]      = 1
        self.mat_struc_Q010[mattot==2]      = 1
        self.mat_struc_Q010[self.field_v>0] = 0
        self.mat_struc_Q020[mattot==2]      = 1
        self.mat_struc_Q020[self.field_v<0] = 0
        self.mat_struc_Q101[mattot==5]      = 1
        self.mat_struc_Q110[mattot==3]      = 1
        self.mat_struc_Q110[self.field_v>0] = 0
        self.mat_struc_Q120[mattot==3]      = 1
        self.mat_struc_Q120[self.field_v<0] = 0
        self.mat_struc_Q011[mattot==6]      = 1
        self.mat_struc_Q011[self.field_v>0] = 0
        self.mat_struc_Q021[mattot==6]      = 1
        self.mat_struc_Q021[self.field_v<0] = 0
        self.mat_struc_Q111[mattot==7]      = 1
        self.mat_struc_Q111[self.field_v>0] = 0
        self.mat_struc_Q121[mattot==7]      = 1
        self.mat_struc_Q121[self.field_v<0] = 0
        
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the SHAP value of the structure and save it
        # ---------------------------------------------------------------------------------------------------------------
        shap_data          = np.zeros((self.shpy,self.shpz,self.shpx,3))
        shap_data[:,:,:,0] = self.field_u
        shap_data[:,:,:,1] = self.field_v 
        shap_data[:,:,:,2] = self.field_w
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q100
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q100      = {"mat_struc":self.mat_struc_Q100,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q100 = structures(data_in=data_struc_Q100)
        self.structures_Q100.separate_structures()
        self.structures_Q100.physicalproperties_structures()
        self.structures_Q100.detect_quadrant()
        self.structures_Q100.segmentation()
        self.structures_Q100.structure_u1u2()
        self.structures_Q100.structure_k123()
        max_struc_Q100       = int(np.max(self.structures_Q100.mat_segment))
        self.shap_Q100       = np.zeros((max_struc_Q100,))
        for nn  in np.arange(max_struc_Q100-1):
            nodes_nn            = np.where(self.structures_Q100.mat_segment==nn+1)
            self.shap_Q100[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q100,"index":"Q100","shap":self.shap_Q100})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q001
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q001      = {"mat_struc":self.mat_struc_Q001,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q001 = structures(data_in=data_struc_Q001)
        self.structures_Q001.separate_structures()
        self.structures_Q001.physicalproperties_structures()
        self.structures_Q001.detect_quadrant()
        self.structures_Q001.segmentation()
        self.structures_Q001.structure_u1u2()
        self.structures_Q001.structure_k123()
        max_struc_Q001       = int(np.max(self.structures_Q001.mat_segment))
        self.shap_Q001       = np.zeros((max_struc_Q001,))
        for nn  in np.arange(max_struc_Q001-1):
            nodes_nn            = np.where(self.structures_Q001.mat_segment==nn+1)
            self.shap_Q001[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q001,"index":"Q001","shap":self.shap_Q001})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q010
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q010      = {"mat_struc":self.mat_struc_Q010,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q010 = structures(data_in=data_struc_Q010)
        self.structures_Q010.separate_structures()
        self.structures_Q010.physicalproperties_structures()
        self.structures_Q010.detect_quadrant()
        self.structures_Q010.segmentation()
        self.structures_Q010.structure_u1u2()
        self.structures_Q010.structure_k123()
        max_struc_Q010       = int(np.max(self.structures_Q010.mat_segment))
        self.shap_Q010       = np.zeros((max_struc_Q010,))
        for nn  in np.arange(max_struc_Q010-1):
            nodes_nn            = np.where(self.structures_Q010.mat_segment==nn+1)
            self.shap_Q010[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q010,"index":"Q010","shap":self.shap_Q010})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q020
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q020      = {"mat_struc":self.mat_struc_Q020,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q020 = structures(data_in=data_struc_Q020)
        self.structures_Q020.separate_structures()
        self.structures_Q020.physicalproperties_structures()
        self.structures_Q020.detect_quadrant()
        self.structures_Q020.segmentation()
        self.structures_Q020.structure_u1u2()
        self.structures_Q020.structure_k123()
        max_struc_Q020       = int(np.max(self.structures_Q020.mat_segment))
        self.shap_Q020       = np.zeros((max_struc_Q020,))
        for nn  in np.arange(max_struc_Q020-1):
            nodes_nn            = np.where(self.structures_Q020.mat_segment==nn+1)
            self.shap_Q020[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q020,"index":"Q020","shap":self.shap_Q020})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q101
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q101      = {"mat_struc":self.mat_struc_Q101,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q101 = structures(data_in=data_struc_Q101)
        self.structures_Q101.separate_structures()
        self.structures_Q101.physicalproperties_structures()
        self.structures_Q101.detect_quadrant()
        self.structures_Q101.segmentation()
        self.structures_Q101.structure_u1u2()
        self.structures_Q101.structure_k123()
        max_struc_Q101       = int(np.max(self.structures_Q101.mat_segment))
        self.shap_Q101       = np.zeros((max_struc_Q101,))
        for nn  in np.arange(max_struc_Q101-1):
            nodes_nn            = np.where(self.structures_Q101.mat_segment==nn+1)
            self.shap_Q101[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q101,"index":"Q101","shap":self.shap_Q101})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q110
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q110      = {"mat_struc":self.mat_struc_Q110,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q110 = structures(data_in=data_struc_Q110)
        self.structures_Q110.separate_structures()
        self.structures_Q110.physicalproperties_structures()
        self.structures_Q110.detect_quadrant()
        self.structures_Q110.segmentation()
        self.structures_Q110.structure_u1u2()
        self.structures_Q110.structure_k123()
        max_struc_Q110       = int(np.max(self.structures_Q110.mat_segment))
        self.shap_Q110       = np.zeros((max_struc_Q110,))
        for nn  in np.arange(max_struc_Q110-1):
            nodes_nn            = np.where(self.structures_Q110.mat_segment==nn+1)
            self.shap_Q110[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q110,"index":"Q110","shap":self.shap_Q110})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q120
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q120      = {"mat_struc":self.mat_struc_Q120,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q120 = structures(data_in=data_struc_Q120)
        self.structures_Q120.separate_structures()
        self.structures_Q120.physicalproperties_structures()
        self.structures_Q120.detect_quadrant()
        self.structures_Q120.segmentation()
        self.structures_Q120.structure_u1u2()
        self.structures_Q120.structure_k123()
        max_struc_Q120       = int(np.max(self.structures_Q120.mat_segment))
        self.shap_Q120       = np.zeros((max_struc_Q120,))
        for nn  in np.arange(max_struc_Q120-1):
            nodes_nn            = np.where(self.structures_Q120.mat_segment==nn+1)
            self.shap_Q120[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q120,"index":"Q120","shap":self.shap_Q120})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q011
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q011      = {"mat_struc":self.mat_struc_Q011,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q011 = structures(data_in=data_struc_Q011)
        self.structures_Q011.separate_structures()
        self.structures_Q011.physicalproperties_structures()
        self.structures_Q011.detect_quadrant()
        self.structures_Q011.segmentation()
        self.structures_Q011.structure_u1u2()
        self.structures_Q011.structure_k123()
        max_struc_Q011       = int(np.max(self.structures_Q011.mat_segment))
        self.shap_Q011       = np.zeros((max_struc_Q011,))
        for nn  in np.arange(max_struc_Q011-1):
            nodes_nn            = np.where(self.structures_Q011.mat_segment==nn+1)
            self.shap_Q011[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q011,"index":"Q011","shap":self.shap_Q011})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q021
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q021      = {"mat_struc":self.mat_struc_Q021,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q021 = structures(data_in=data_struc_Q021)
        self.structures_Q021.separate_structures()
        self.structures_Q021.physicalproperties_structures()
        self.structures_Q021.detect_quadrant()
        self.structures_Q021.segmentation()
        self.structures_Q021.structure_u1u2()
        self.structures_Q021.structure_k123()
        max_struc_Q021       = int(np.max(self.structures_Q021.mat_segment))
        self.shap_Q021       = np.zeros((max_struc_Q021,))
        for nn  in np.arange(max_struc_Q021-1):
            nodes_nn            = np.where(self.structures_Q021.mat_segment==nn+1)
            self.shap_Q021[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q021,"index":"Q021","shap":self.shap_Q021})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q111
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q111      = {"mat_struc":self.mat_struc_Q111,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q111 = structures(data_in=data_struc_Q111)
        self.structures_Q111.separate_structures()
        self.structures_Q111.physicalproperties_structures()
        self.structures_Q111.detect_quadrant()
        self.structures_Q111.segmentation()
        self.structures_Q111.structure_u1u2()
        self.structures_Q111.structure_k123()
        max_struc_Q111       = int(np.max(self.structures_Q111.mat_segment))
        self.shap_Q111       = np.zeros((max_struc_Q111,))
        for nn  in np.arange(max_struc_Q111-1):
            nodes_nn            = np.where(self.structures_Q111.mat_segment==nn+1)
            self.shap_Q111[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q111,"index":"Q111","shap":self.shap_Q111})
        
        # ---------------------------------------------------------------------------------------------------------------
        # Calculate the structure Q121
        # ---------------------------------------------------------------------------------------------------------------
        data_struc_Q121      = {"mat_struc":self.mat_struc_Q121,"field_1":self.vel_u,"field_2":self.vel_v,
                                "field_3":self.vel_w,"flag_sign":False,"uvw_folder":self.uvw_folder,
                                "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                "shap_file":self.shap_file}
        self.structures_Q121 = structures(data_in=data_struc_Q121)
        self.structures_Q121.separate_structures()
        self.structures_Q121.physicalproperties_structures()
        self.structures_Q121.detect_quadrant()
        self.structures_Q121.segmentation()
        self.structures_Q121.structure_u1u2()
        self.structures_Q121.structure_k123()
        max_struc_Q121       = int(np.max(self.structures_Q121.mat_segment))
        self.shap_Q121       = np.zeros((max_struc_Q121,))
        for nn  in np.arange(max_struc_Q121-1):
            nodes_nn            = np.where(self.structures_Q121.mat_segment==nn+1)
            self.shap_Q121[nn] += np.linalg.norm(shap_data[nodes_nn])
        self.save_struc_Q(data_in={"structure":self.structures_Q121,"index":"Q121","shap":self.shap_Q121})
            
               
    def save_struc_Q(self,data_in={"structure":[],"index":"Qxxx","shap":[]}):
        """
        .................................................................................................................
        # save_struc_Q
        .................................................................................................................
        Function to save the parameters of the structure

        Parameters
        ----------
        data_in : dict, optional
            Name of the folder and file of the file of the previous data.
            The default is {"structure":[],"index":"Qx","shap":[]}.
            Data:
                - structure : structure to save
                - index     : quadrant to save
                - shap      : shap values
        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        structure = data_in["structure"]
        index     = str(data_in["index"])
        shap      = data_in["shap"]
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the folder if not existing
        # ---------------------------------------------------------------------------------------------------------------
        try:
            print("Create folder",flush=True)
            os.mkdir(self.folder)
        except:
            print("Folder "+str(self.folder)+" is already created.",flush=True)
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        
        # ---------------------------------------------------------------------------------------------------------------
        # Create the file and save the information
        # ---------------------------------------------------------------------------------------------------------------
        hf = h5py.File(file_Q_ii,'a')
        hf.create_dataset('Qs_'+index,data=structure.mat_struc)
        hf.create_dataset('Qs_event_'+index,data=structure.mat_event)
        hf.create_dataset('Qs_segment_'+index,data=structure.mat_segment)
        hf.create_dataset('Qs_segment_filtered_'+index,data=structure.mat_segment_filtered)
        hf.create_dataset('dim_x_'+index,data=structure.dim_x)
        hf.create_dataset('dim_z_'+index,data=structure.dim_z)
        hf.create_dataset('dim_y_'+index,data=structure.dim_y)
        hf.create_dataset('ymin_'+index,data=structure.ymin)
        hf.create_dataset('ymax_'+index,data=structure.ymax)
        hf.create_dataset('vol_'+index,data=structure.vol)
        hf.create_dataset('volbox_'+index,data=structure.boxvol)
        hf.create_dataset('cg_xbox_'+index,data=structure.cg_xbox)
        hf.create_dataset('cg_ybox_'+index,data=structure.cg_ybox)
        hf.create_dataset('cg_zbox_'+index,data=structure.cg_zbox)
        hf.create_dataset('cg_x_'+index,data=structure.cg_x)
        hf.create_dataset('cg_y_'+index,data=structure.cg_y)
        hf.create_dataset('cg_z_'+index,data=structure.cg_z)
        hf.create_dataset('event_'+index,data=structure.event)
        hf.create_dataset('uv_uvtot_'+index,data=structure.u1u2)
        hf.create_dataset('k_ktot_'+index,data=structure.k123)
        try:
            hf.create_dataset('shap_'+index,data=shap)
        except:
            pass
        hf.close()
        
    def read_struc_Q(self):
        """
        .................................................................................................................
        # save_struc_Q
        .................................................................................................................
        Function to read the quadrants of the structures

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Create the path to the file
        # ---------------------------------------------------------------------------------------------------------------
        file_Q    = self.folder+"/"+self.file
        file_Q_ii = file_Q.replace("$INDEX$",str(self.index))
        if self.nsamples is None:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$","")
        else:
            file_Q_ii = file_Q_ii.replace("$NSAMPLES$",str(self.nsamples))
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the structures
        # ---------------------------------------------------------------------------------------------------------------
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q100"})
        self.structures_Q100 = data_out["structure"]
        self.shap_Q100       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q001"})
        self.structures_Q001 = data_out["structure"]
        self.shap_Q001       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q010"})
        self.structures_Q010 = data_out["structure"]
        self.shap_Q010       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q020"})
        self.structures_Q020 = data_out["structure"]
        self.shap_Q020       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q101"})
        self.structures_Q101 = data_out["structure"]
        self.shap_Q101       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q110"})
        self.structures_Q110 = data_out["structure"]
        self.shap_Q110       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q120"})
        self.structures_Q120 = data_out["structure"]
        self.shap_Q120       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q011"})
        self.structures_Q011 = data_out["structure"]
        self.shap_Q011       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q021"})
        self.structures_Q021 = data_out["structure"]
        self.shap_Q021       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q111"})
        self.structures_Q111 = data_out["structure"]
        self.shap_Q111       = data_out["shap"]
        data_out             = self.read_quadrant(data_in={"file":file_Q_ii,"index":"Q121"})
        self.structures_Q121 = data_out["structure"]
        self.shap_Q121       = data_out["shap"]
        
    def read_quadrant(self,data_in={"file":"-","index":"Qxxx"}):
        """
        .................................................................................................................
        # read_quadrant
        .................................................................................................................
        Function to read each quadrant of the structures

        Returns
        -------
        None.

        """
        # ---------------------------------------------------------------------------------------------------------------
        # Import packages
        # ---------------------------------------------------------------------------------------------------------------
        from py_bin.py_class.structures import structures
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the data
        # ---------------------------------------------------------------------------------------------------------------
        index     = str(data_in["index"])
        file_Q_ii = str(data_in["file"])
        
        # ---------------------------------------------------------------------------------------------------------------
        # Read the rest of the data
        # ---------------------------------------------------------------------------------------------------------------
        data_struc                     = {"mat_struc":[],"field_1":self.field_u,"field_2":self.field_v,
                                          "field_3":self.field_w,"flag_sign":True,"uvw_folder":self.uvw_folder,
                                          "uvw_file":self.uvw_file,"dx":self.down_x,"dy":self.down_y,"dz":self.down_z,
                                          "L_x":self.L_x,"L_y":self.L_y,"L_z":self.L_z,"rey":self.rey,"utau":self.utau,
                                          "sym_quad":self.sym_quad,"filvol":self.filvol,"shap_folder":self.shap_folder,
                                          "shap_file":self.shap_file}
        structure                      = structures(data_in=data_struc)
        file                           = h5py.File(file_Q_ii,'r')
        structure.mat_struc            = np.array(file['Qs_'+index])
        structure.mat_event            = np.array(file['Qs_event_'+index])
        structure.mat_segment          = np.array(file['Qs_segment_'+index])
        structure.mat_segment_filtered = np.array(file['Qs_segment_filtered_'+index])
        structure.dim_x                = np.array(file['dim_x_'+index])
        structure.dim_y                = np.array(file['dim_y_'+index])
        structure.dim_z                = np.array(file['dim_z_'+index])
        structure.ymin                 = np.array(file['ymin_'+index])
        structure.ymax                 = np.array(file['ymax_'+index])
        structure.vol                  = np.array(file['vol_'+index])
        structure.boxvol               = np.array(file['volbox_'+index])
        structure.cg_xbox              = np.array(file['cg_xbox_'+index])
        structure.cg_ybox              = np.array(file['cg_ybox_'+index])
        structure.cg_zbox              = np.array(file['cg_zbox_'+index])
        structure.cg_x                 = np.array(file['cg_x_'+index])
        structure.cg_y                 = np.array(file['cg_y_'+index])
        structure.cg_z                 = np.array(file['cg_z_'+index])
        structure.event                = np.array(file['event_'+index])
        structure.u1u2                 = np.array(file['uv_uvtot_'+index])
        structure.k_ktot               = np.array(file['k_ktot_'+index])
        try:
            shap                       = np.array(file['shap_'+index])
        except:
            pass
        data_out = {"structure":structure,"shap":shap}
        return data_out